---
- name: Install node exporter
  hosts: all
  become: yes

  tasks:
    - name: Create node_exporter group
      group:
        name: node_exporter
        state: present

    - name: Create user for node-exporter
      user:
        name: node_exporter
        group: node_exporter
        shell: /bin/false
        create_home: false
        state: present

    - name: Download tgz archive of node-exporter binary file
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /opt

    - name: Unarchive node-exporter archive
      unarchive:
        remote_src: true
        src: /opt/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /opt

    - name: Copy binary file to /usr/local/bin
      copy:
        remote_src: true
        src: /opt/node_exporter-1.3.1.linux-amd64/node_exporter
        dest: /usr/local/bin
        mode: 751
        owner: node_exporter
        group: node_exporter

    - name: Link daemon file
      file:
        src: /opt/system/node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
        state: link

    - name: Reload daemons
      systemd:
        name: node_exporter.service
        daemon_reload: true
        state: started